server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: 'http://localhost:8000'
          predicates:
            - Path=/products/api/v1/**
          filters:
#            - StripPrefix=3
#            - EjemploCookie=Hola mi mensaje personalizado, usuario, kathesama
        - id: item-service
          uri: 'http://localhost:8001'
          predicates:
            - Path=/items/api/v1/**
          filters:
#            - StripPrefix=3
#            - AddRequestHeader=token-request, 123456
#            - AddResponseHeader=token-response, 12345678
#            - SetResponseHeader=Content-Type, text/plain
#            - AddRequestParameter=nombre, andres
eureka:
  client:
    register-with-eureka: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
