server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-boot-realm-dev
          jwk-set-uri: http://localhost:9090/realms/spring-boot-realm-dev/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/api/v1/**
          filters:
            - ExampleCookie=Hello world, user, kathesama
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/api/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/api/**
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: spring-client-credentials-id

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
