server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          order: 8000
          predicates:
            - Path=/products/api/v1/**
          filters:
            - ExampleCookie=Hello world, user, kathesama
#            - StripPrefix=1
        - id: item-service
          uri: lb://item-service
          order: 8001
          predicates:
            - Path=/items/api/**
          filters:
#            - StripPrefix=1
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
